---
title: "Untitled"
author: "pss"
date: "February 19, 2018"
output: html_document
params:
  save: 1
  sub: !r c(5)
  task: "localizer"
  flip_hz: 10
  n_phase: 16
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(magrittr)


if(params$task == "contrast"){
  n_grating_per_side = 5
  scan_dur_sec = 420
}else if(params$task == "localizer"){
  n_grating_per_side = 10
    scan_dur_sec = 336
}
n_grating = n_grating_per_side * 2


shifter <- function(x, n = 1) {
  if (n == 0) x else c(tail(x, -n), head(x, n))
}

make_phase <- function(d, type, n_phase = params$n_phase){
  phases <- seq(0, 180 - n_phase, n_phase)
  n <- nrow(d)
  
  phase <- rep(sample(phases, size = n/2, replace = TRUE), each=2)
  if(type == "offset"){
    phase <- c(sample(phases,1), phase[1:(length(phase)-1)])
  }
  if((n %% 2) == 1){
    phase <- c(phase, sample(phases,1))
  }
  
  return(phase)
}


```


```{r get_ga_dump}

files <- list.files(path = "ga_dump", pattern = glue::glue( ".*{params$task}_run-.*ga_events.tsv"), recursive = TRUE, full.names = TRUE )
finfo <- file.info(files, extra_cols = FALSE) %>%
  as_tibble() %>%
  tibble::rownames_to_column(var = "filename") %>%
  select(filename) %>%
  mutate(events = map(filename, read_tsv, col_types = c(onset_expected = col_double(), 
                                                        duration_expected = col_double(),
                                                        orientation = col_character(),
                                                        contrast = col_character(),
                                                        side = col_character(),
                                                        trial = col_double(),
                                                        subject = col_double(),
                                                        trial_type = col_character(),
                                                        run = col_double()))) %>%
  unnest(events) %>%
  filter(subject %in% params$sub)

```


```{r main_data}

d_main <- finfo %>%
  group_by(side, run, subject) %>%
  nest() %>%
  mutate(data = map(data, ~.x %>% 
                      arrange(trial) %>% 
                      mutate(iti_expected = 
                               case_when( trial == 1 ~ lead(onset_expected, default = scan_dur_sec) - duration_expected ,
                                          trial > 1 ~ lead(onset_expected, default = scan_dur_sec) - duration_expected - onset_expected)))) %>%
  unnest() %>%
  mutate(n_flip_in_trial = (duration_expected + iti_expected) * params$flip_hz
         , exitflag = NA_character_ 
         , response = "NO RESPONSE"
         , correct = NA
  )

if(params$save){
  for(sub in params$sub){
    for(r in unique(d_main$run)){
      d_main %>%
        filter(run == r, subject == sub) %>%
        filter(trial_type == "grating") %>%
        readr::write_tsv(., file.path(glue::glue("sub-{sprintf('%02d', sub)}"), glue::glue("sub-{sprintf('%02d', sub)}_task-{params$task}_run-{sprintf('%02d', r)}_grating.tsv")))
      
      d_main %>%
        filter(run == r, subject == sub) %>%
        filter(trial_type == "dim") %>%
        readr::write_tsv(., file.path(glue::glue("sub-{sprintf('%02d', sub)}"), glue::glue("sub-{sprintf('%02d', sub)}_task-{params$task}_run-{sprintf('%02d', r)}_dim.tsv")))
      
    }
  }
}
```


Note that, for this simple experiment, we're somewhat conflating flip sampling rate with response sampling rate. This is pretty fast (in that flips happen often), and relatively easy to program (becaues we can just index into the tInfo dataframe), but this does prevent the recording of responses given in very quick succession (result might be faster, overall).

```{r tick_info}

is_close <- function(a,b, tolerance = params$flip_hz/1000){
  return(abs(a-b) <= tolerance)
}


d_tInfo <- d_main %>%
  group_by(trial_type, trial, side, run, subject) %>%
  nest() %>% 
  mutate(data = map(data, ~crossing(.x, flip_in_trial = 1:.x$n_flip_in_trial))) %>%
  unnest() %>%
  group_by(trial_type, side, run, subject) %>%
  nest() %>% 
  mutate(data = map(data, ~.x %>% mutate(flip = 1:nrow(.x)))) %>%
  unnest() %>%
  mutate(vbl_expected = (flip-1) * (1/params$flip_hz)) %>%
  mutate(event = case_when( is_close(vbl_expected, onset_expected) ~ "trial_start",
                            (vbl_expected > onset_expected) & (vbl_expected < onset_expected + duration_expected) ~ "trial_going",
                            is_close(vbl_expected, onset_expected + duration_expected) ~ "return_to_base_contrast",
                            TRUE ~ "at_base_contrast" ),
         contrast = case_when(trial_type == "grating" ~ if_else(event %in% c("at_base_contrast", "return_to_base_contrast"), "0", contrast),
                              trial_type == "dim" ~ if_else(event %in% c("at_base_contrast", "return_to_base_contrast"), "1", contrast)),
         answer = case_when(trial_type == "grating" ~ "n/a",
                            trial_type == "dim" ~ if_else(contrast == "1", "NO RESPONSE", "1!"))
  ) %>%
  mutate(vbl = NaN
         , stimulus_onset_time = NaN
         , flip_timestamp = NaN
         , beampos = NaN
         , missed = NaN
         , press_time = NaN
  )


if(params$save){
  for(sub in params$sub){
    for(r in unique(d_tInfo$run)){
      d_tInfo %>% 
        filter(run == r & subject == sub) %>%
        readr::write_tsv(., file.path(glue::glue("sub-{sprintf('%02d', sub)}"), glue::glue("sub-{sprintf('%02d', sub)}_task-{params$task}_run-{sprintf('%02d', r)}_tInfo.tsv")))
      
    }
  }
}

```

