---
title: "Untitled"
author: "pss"
date: "February 19, 2018"
output: html_document
params:
  save: 1
  extras: 0
  sub: !r c(6)
  task: "contrast"
  type: "data" # either data or robo (only robo for testing)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(magrittr)


if (params$task == "contrast"){
  col_types <- cols(trial_type = col_character(),
                   side = col_character(),
                   run = col_integer(),
                   subject = col_integer(),
                   trial = col_integer(),
                   duration_expected = col_double(),
                   onset_expected = col_double(),
                   orientation = col_double(),
                   exitflag = col_character(),
                   response = col_character(),
                   flip_in_trial = col_integer(),
                   flip = col_integer(),
                   event = col_character(),
                   answer = col_character(),
                   contrast = col_double())
}else if (params$task == "localizer"){
    col_types <- cols(trial_type = col_character(),
                   side = col_character(),
                   run = col_integer(),
                   subject = col_integer(),
                   trial = col_integer(),
                   duration_expected = col_character(),
                   onset_expected = col_character(),
                   exitflag = col_character(),
                   response = col_character(),
                   flip_in_trial = col_integer(),
                   flip = col_integer(),
                   event = col_character(),
                   answer = col_character(),
                   contrast = col_double(),
                   iti_expected = col_character()
                   )
}

```


```{r get_ga_dump}

files <- list.files(path = file.path(params$type), pattern = glue::glue( "sub-{sprintf('%02d', params$sub)}.*{params$task}.*tInfo.tsv"), recursive = TRUE, full.names = TRUE )

tInfo <- file.info(files, extra_cols = FALSE) %>%
  as_tibble() %>%
  tibble::rownames_to_column(var = "filename") %>%
  select(filename) %>%
  mutate(events = map(filename, read_tsv, col_types = col_types, guess_max = 10000)
  ) %>%
  unnest(events) %>%
  filter(subject %in% params$sub) %>%
  select(-filename)

```


```{r main_data}

d <- tInfo %>%
  group_by(run) %>%
  nest() %>%
  mutate(firstfliptime = map_dbl(data, ~min(.x$vbl, na.rm = TRUE))) %>%
  unnest() %>%
  group_by(subject, run, trial_type, side, trial) %>%
  nest() 


# in the following, the trial_resp_open vs. duration is because with sub-05, 
# some of the dimming trials never had a 'return_to_base_contrast' event
if (params$task == "contrast"){
  d %<>%
    mutate(orientation = map_dbl(data, ~ unique(.x$orientation)),
           contrast = map_dbl(data, ~max(.x$contrast)),
           onset = map_dbl(data, ~ .x %>% filter(event == 'trial_start') %>%
                             use_series(vbl) - unique(.x$firstfliptime)),
           duration = map_dbl(data, ~.x[min(which(.x$event %in% c('return_to_base_contrast', "trial_resp_open"))),] %>%
                                use_series(vbl) - unique(.x$firstfliptime)) - onset) %>%
    mutate(con = plyr::mapvalues(contrast, from = unique(contrast), to = str_c("con", unique(contrast), sep = "-")),
           ori = plyr::mapvalues(orientation, from = unique(orientation), to = str_c("ori", unique(orientation), sep = "-")),
           tmp = trial_type,
           task = params$task) %>%
    unite(trial_type, c(con,ori)) %>%
    mutate(trial_type = if_else(tmp == "grating", trial_type, tmp)) %>%
    select(onset, duration, trial_type, contrast, orientation, run, subject, task) %>%
    arrange(onset)
  
}else if (params$task == "localizer"){
  d %<>%
    mutate(orientation = "checkerboard",
           contrast = map_dbl(data, ~max(.x$contrast)),
           onset = map_dbl(data, ~ .x %>% filter(event == 'trial_start') %>%
                             use_series(vbl) - unique(.x$firstfliptime)),
           duration = map_dbl(data, ~.x[min(which(.x$event %in% c('return_to_base_contrast', "trial_resp_open"))),] %>%
                                use_series(vbl) - unique(.x$firstfliptime)) - onset) %>%
    mutate(tmp = trial_type,
           task = params$task) %>%
    mutate(trial_type = if_else(tmp == "grating", "checkerboard", tmp)) %>%
    select(onset, duration, trial_type, contrast, orientation, run, subject, task) %>%
    arrange(onset)
}

# extras used just for checking
if (params$extras){
  d %<>%
    mutate(onset_expected = map_dbl(data, ~ .x %>% filter(event == 'trial_start') %>%
                                      use_series(vbl_expected)),
           duration_expected = map_dbl(data, ~.x %>% filter(event == 'return_to_base_contrast') %>%
                                         use_series(vbl_expected)) - onset_expected)
}


# the screen failed during run 4 of sub-05. Probably only ~30s were lost, but were eliminating the last 1 min of events to be safe
if ((params$sub == 5) & (params$task == "contrast")){
  d %<>%
    filter(not(run == 4 & onset > 360))
}
  

if(params$save & not(params$extras)){
  for(sub in params$sub){
    for(r in unique(d$run)){
      d %>%
        filter(run == r, subject == sub) %>%
        readr::write_tsv(., file.path(params$type, glue::glue("sub-{sprintf('%02d', sub)}"), 'func', glue::glue("sub-{sprintf('%02d', sub)}_task-{params$task}_run-{sprintf('%02d', r)}_events.tsv")))
      
    }
  }
}

```

